### Numpy

it is a fundamental library for scientific computing in python.
It provides support for arrays and matrices / vectors(row or column matrix),
along with a collection of mathematical functions to operate on these data structures.

In [ ]:
!pip install numpy

A simple question: as we have list,dict,tuple then why do we need array, matrices (numpy)?
because array are super fast and in machine learning or for other computation where we have a large set of data of same data-types then we use array or matrix for fast computation,

### Numpy Array/matrix operation

In [1]:
import numpy as np

### create array using numpy
#create a 1D array
arr1 = np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.shape) #(5,) # 5 elements and ,_ blank means there is no specific row and 
                  # column  in the array.
                  # the array is single dimension array(no rows & columns) 
                  # meaning there are no specifics rows and columns in the array.
                  # this is not 1 row and 5 columns
arr1

<class 'numpy.ndarray'>
(5,)


array([1, 2, 3, 4, 5])

In [6]:
# when we change 1D array to 2D array then we can say there are rows & columns.
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row 5 columns
# here 2 backets mean 2D array

array([[1, 2, 3, 4, 5]])

In [11]:
arr2.reshape(1,4) #its not possible to initialize list with 
                  # 5 elements to 4 columns.

ValueError: cannot reshape array of size 5 into shape (1,4)

In [ ]:
print(arr2.shape) # why still (5,) after reshape? because reshape does not change the original array it just returns a new array with the new shape.
                  # so the original array is still 1D array with 5 elements and no specific row and column. 
                  # the array is single dimension array(no rows & columns) 
                  # meaning there are no specifics rows and columns in the array.
                  # but when we reshape the array to 1 row and 5 columns then we can say there are rows & columns.
arr2.reshape(1,5).shape # (1,5) # 1 row and 5 columns here we can say there are rows & columns.but the original array is still 1D array with 5 elements and no specific row and column.because reshape does not change the original array it just returns a new array with the new shape.

(5,)


(1, 5)

In [ ]:
# 2D array
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [8]:
# 2D array 
arr3 = np.array([[1,2,3,4], [5,6,7,8]])
print(arr3)
arr3.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
# some in-build functions
a = np.arange(0,20,2).reshape(2,5) # 0 to 20 with step size of 2 and reshape to 2 rows and 5 columns
print(a)
print(a.shape)


[[ 0  2  4  6  8]
 [10 12 14 16 18]]
(2, 5)


In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of numpy array
arr4 = np.array([[1,2,3],[4,5,6]])

print("Array: \n", arr4)
print("Shape: ", arr4.shape)
print("Number of Dimension: ", arr4.ndim)
print("Size or Total number of elements: ", arr4.size)
print("Data type: ", arr4.dtype)
print("Item size (in bytes): ", arr4.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of Dimension:  2
Size or Total number of elements:  6
Data type:  int64
Item size (in bytes):  8


### Numpy Vectorize operation.

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Elementwise Addition
print("Addition of two vector: ", arr1+arr2)

# Elementwise Substraction
print("Substraction of two vector: ", arr1-arr2)

# Elementwise multiplication
print("Multiplication of two vector: ", arr1*arr2)

# Elementwise Division
print("Division of two vector: ", arr1/arr2)

# all the return type will also be an array/vector

Addition of two vector:  [11 22 33 44 55]
Substraction of two vector:  [ -9 -18 -27 -36 -45]
Multiplication of two vector:  [ 10  40  90 160 250]
Division of two vector:  [0.1 0.1 0.1 0.1 0.1]


In [23]:
### Universal fucntion - meaning funcs that apply to the entire array.
arr = np.array([2,3,4,5,6])
#square root
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
### Array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Accesing to the element of the array
    #to do that we need to know about the row,columns
print(arr.shape)
print(arr[0][0])
print(arr[2][3])
# first row except first element
print(arr[0][1:])
print()

print("print 2nd and 3rd row: ")
print(arr[1:])

# be concious, [ , ] is the best way rather than [][]

print("print the elements 7,8,11,12: ")
print(arr[1:, 2:])

print("print the elements 3,4,7,8: ")
print(arr[:2, 2:])

print("print the elements 6,7,10,11: ")
a = arr[1: ,1:3]
print(a)


(3, 4)
1
12
[2 3 4]

print 2nd and 3rd row: 
[[ 5  6  7  8]
 [ 9 10 11 12]]
print the elements 7,8,11,12: 
[[ 7  8]
 [11 12]]
print the elements 3,4,7,8: 
[[3 4]
 [7 8]]
print the elements 6,7,10,11: 
[[ 6  7]
 [10 11]]


In [47]:
### Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [48]:
arr[1:, 2:] = 200
print(arr)

[[100   2   3   4]
 [  5   6 200 200]
 [  9  10 200 200]]


### practical example

In [ ]:
### Statistical concept (Normalization)
# Z-score Normalization =  is a technique used to standardize the values of a dataset by transforming them to have a mean of 0 and a standard deviation of 1. This is done by subtracting the mean from each data point and then dividing the result by the standard deviation. The formula for Z-score normalization is:
data = np.array([1,2,3,4,5])

#calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#Normalize the data
normalized_data = (data - mean)/std_dev
print("Normalize data: ", normalized_data)

Normalize data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
### Central Tendency functions:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
print(np.mean(data))
# Median
print(np.median(data))
# Standart Deviation
print(np.std(data))
# Variance
print(np.var(data))


5.5
5.5
2.8722813232690143
8.25


In [ ]:
### Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)
print(data[data>5])
print(data[(data>4) & (data%2==0)])
# we will need this a lot in pandas to work with the large excel datas

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[ 6  8 10]
